### ISSUE TITLE
marker-descs "(?i).*maintenance*" How should I go about writing

### ISSUE THREAD

**Issue by HansOffice** [BGHDDevelopment/PlayerBalancer#31]
If I want to write &c game in the state can not let the player into the game, how should I go about writing it? Tried using full word match then it didn't work. Can you give an example? Please!

**Comment by BGHDDevelopment** [comment]
Can you show the things you have tried? Screenshots of what the MOTD and what you put in the config would be a great help.
Feel free to reach out on Discord for faster responses: https://discord.gg/bghddevelopment

**Comment by HansOffice** [comment]
&nbsp; &nbsp; marker-descs=[
&nbsp; &nbsp; &nbsp; "(?i).*游戏中*", # match if contains (regex)
&nbsp; &nbsp; &nbsp; "&amp;c游戏中" # match if exactly equal

The motd written in the bedwarsrel is
&nbsp; motds:
&nbsp; &nbsp; lobby: '&amp;a等待中...'
&nbsp; &nbsp; running: '&amp;c游戏中'
&nbsp; &nbsp; stopped: '&amp;c停止'
&nbsp; &nbsp; full: '&amp;c满人'





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月25日(星期三) 凌晨4:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BGHDDevelopment/PlayerBalancer] marker-descs &quot;(?i).*maintenance*&quot; How should I go about writing (Issue #31)





 
Can you show the things you have tried? Screenshots of what the MOTD and what you put in the config would be a great help.
 Feel free to reach out on Discord for faster responses: https://discord.gg/bghddevelopment

**Comment by BGHDDevelopment** [comment]
While it should not matter I am just thinking that it may be the characters causing it to not work. Have you tried just doing "stopped" or "full" rather then the other characters? As these servers would most likely not be public-facing the MOTD should not really mater.
