### ISSUE TITLE
Updata watherfall-1.19

### ISSUE THREAD

**Issue by MCJiaoLong** [BGHDDevelopment/PlayerBalancer#32]
![Error Logs](https://user-images.githubusercontent.com/75253383/172986867-3b723fb6-4ec7-4409-bed1-f69e39a23797.png)

**Comment by BGHDDevelopment** [comment]
I can look into this tomorrow. Though the yellow message may provide some reasoning. Is there anything blocking the connection to Spigot?

**Comment by BGHDDevelopment** [comment]
Cannot reproduce.
