### ISSUE TITLE
ajqueue support

### ISSUE THREAD

**Issue by Chiquis2005** [BGHDDevelopment/PlayerBalancer#33]
https://user-images.githubusercontent.com/44950448/186088684-7dcff63d-ee02-4999-b389-c053ecfc6814.mp4

https://user-images.githubusercontent.com/44950448/186088701-4ba4e891-3783-4c47-88b5-68c611a37a06.mp4

![image](https://user-images.githubusercontent.com/44950448/186088738-8b869aea-a8fb-4661-b21a-f83376a8f98a.png)

**Comment by BGHDDevelopment** [comment]
I have replied directly on Discord. We can continue the discussion there.
