### ISSUE TITLE
In Velocity, non-administrators are unable to use commands to enter servers.

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [BGHDDevelopment/PlayerBalancer#43]
When using Velocity, there may be an issue where commands for server groups cannot be accessed without administrator permissions. The command is not found in such cases, while administrators can use it normally.
![6 4O12AANS4)QE %U9SVAK](https://github.com/BGHDDevelopment/PlayerBalancer/assets/50231954/a538205a-3feb-47b4-ad9d-b5bb87c00844)
![6%Y3{KQBD{(4SIFNSIGM{RJ](https://github.com/BGHDDevelopment/PlayerBalancer/assets/50231954/ec9afb29-5fdb-49d3-9b5a-0b6b92ba830d)

**Comment by BGHDDevelopment** [comment]
Thanks for the info. I did not make the velocity port and have never used its API but I will see what I can find out.

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱
