### ISSUE TITLE
ConcurrentModificationException for addon

### ISSUE THREAD

**Issue by kazuhaAyato** [BGHDDevelopment/PlayerBalancer#48]
While i'm using the pbaddon on sipgot 1.12.2 (java17), it keeps spamming my console with ConcurrentModificationException.
![image](https://github.com/BGHDDevelopment/PlayerBalancer/assets/66939153/ba567097-51b6-4e14-9770-cebb2bdd401a)

**Comment by BGHDDevelopment** [comment]
Go ahead and test the new release. Please re-open if this issue still happens.

**Comment by kazuhaAyato** [comment]
![image](https://github.com/BGHDDevelopment/PlayerBalancer/assets/66939153/8b67df66-bfd0-4ffa-bc7c-d853ada5035b)
Unfortunately :(
